let word = "Men Lenkeranda yasayiram. Men";
// word = "limon";
let result;
result = word.length;
result = word[3];
result = word.slice(0, 3);
result = word.slice(3);
result = word.slice(2, 10);
result = word.substring(-4);
// result = word.replace("Men", "sen");
// result = word.replaceAll("Men", "sen");
result = word.toUpperCase();
result = word.toLowerCase();
// result = word.concat("Masallida yasayiram");
result = word.trim();
result = word.padEnd(10, "*");
result = word[0] + word.padStart(10, "*");
result = word.charAt(2);
result = word.charCodeAt(2);
result = word.split("e");
console.log(result);
